name: Build PyOpenGL-accelerate wheels with manylinux

on:
  push:
    branches: [develop,master]

jobs:

  wheels:
    name: Build architecture-specific wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.3
      with:
        package_dir: './accelerate'
        output_dir: './accelerate/dist'
      env:
        BUILD_EXTENSION: yes
        CIBW_SKIP: 'pp*'

    - name: Save wheels
      uses: actions/upload-artifact@v3
      with:
        path: accelerate/dist/*.whl
